### ISSUE TITLE
Cannot resolve symbol 'Assertions'

### ISSUE THREAD

**Issue by SGsolod** [SGsolod/first_autotest#1]
![Снимок экрана (49)](https://user-images.githubusercontent.com/97279807/155902815-faac03ad-24bf-4a33-9ecd-9d964f41a179.png)

![Снимок экрана (48)](https://user-images.githubusercontent.com/97279807/155902753-d36102a4-e0c2-45ed-8e85-eb268c584137.png)

**Comment by F1rell** [comment]
Здравствуйте, в данной задаче Main не нужен, вы туда написали часть теста. Логика уже записана в BonusService, вам остаётся только написать код bonusServiceTest  который уже предоставлен в условиях задачи, а после дописать ещё пару тестов на ваше усмотрение.
